baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "iamjonfry"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:slug/"
    page = "/:title/"

[params]
    description = "iamjonfry.com"
    twitter = "https://twitter.com/jonfry22"
    github = "https://github.com/JonathonFry/"

    [params.logo]
    url = "fry.png"
    width = 50
    height = 50
