baseurl = "https://iamjonfry.com/"
languageCode = "en-us"
title = "iamjonfry"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-50203596-1"
disqusShortname = "iamjonfry"

[permalinks]
    post = "/:slug/"
    page = "/:title/"

[params]
    description = "iamjonfry.com"
    twitter = "https://twitter.com/jonfry22"
    github = "https://github.com/JonathonFry/"

    [params.logo]
    url = "fry.png"
    width = 50
    height = 50

[[menu.main]]
    name = "code"
    url = "/tags/code/"

[[menu.main]]
      name = "photography"
      url = "/tags/photography/"
